name: Build APKs
on:
  workflow_dispatch: {}   # shows "Run workflow"
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Install platforms & build tools
        run: sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Build APKs
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.7'
          arguments: ':deviceapp:assembleDebug :wearapp:assembleDebug'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: APKs
          path: |
            deviceapp/build/outputs/apk/debug/*-debug.apk
            wearapp/build/outputs/apk/debug/*-debug.apk
